name: Checks

on: [push, pull_request]

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup latest deno version
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Run deno fmt
        run: deno fmt --check *.tsx components/*.tsx

      - name: Run deno lint
        run: deno lint --unstable *.tsx components/*.tsx